# -*- coding: utf-8 -*-
"""Archivo principal para el echobot. Main File for the echobot"""
from fbmq import Page
from flask import Flask, request
import random

# Generated token in the facebook web page
PAGE_ACCESS_TOKEN = "EAAEyhjxiH3IBAHb3J9yzCH0ucLSC8J9EYp8yFNLnfrXGZAsI6IKbdZCZCeZBPqn6Rs8GmZA54PhNQC7wvpmeLx9em42FOZBXqcCfMfnqOmTnnOExnjijQpYr5qBL1VXJxUy10jZBsmCBAQ6fhSIiPPyLvUvLZCh3WTqMPJ4ENtQHKAZDZD"
# Token generated by us
VERIFY_TOKEN = "EchoBotChido" # If you change this token, verify that you changed it too in the webhook configuration.

app = Flask(__name__)
page = Page(PAGE_ACCESS_TOKEN) # We make the facebook page instance

GREETING_KEYWORDS = ("hello", "hi", "greetings", "sup", "what's up", "good morning", "good afternoon")

GREETING_RESPONSES = ["'sup bro", "hey", "*nods*", "hey you get my snap?"]

@app.route('/')
def hello_world():
    """The server main page."""
    return 'Inicio del servidor'

def check_for_greeting(sentence):
    """If any of the words in the user's input was a greeting, return a greeting response"""
    for word in sentence.words:
        if word.lower() in GREETING_KEYWORDS:
            return random.choice(GREETING_RESPONSES)

@app.route('/webhook', methods=['GET', 'POST'])
def webhook():
    """El método que se ejecuta cuando Facebook se conecta. This method executes as Facebook connect to us."""
    if request.method == 'POST':  # if the message is a POST, we handle it with message_handler. Si el mensaje es POST, se maneja con el message_handler
        # Facebook sends the user messages with a POST. Facebook manda los mensajes del usuario con un POST.
        page.handle_webhook(request.get_data(as_text=True))
        return 'ok'
    elif request.method == 'GET':  # if the message is a GET, we handle it here. 
        # The first you configure the webhook, FB sends a GET to your webhook to verify that it really is you, and you're not working on someone's else page.
        if request.args.get('hub.verify_token') == VERIFY_TOKEN:
            # If the verify token in the url matches our verify token we answer with the challenge to prove our identity.
            return request.args.get('hub.challenge')
        return 'Wrong Verify token'


@page.handle_message
def message_handler(event):
    """Este método se ejecuta cuando nos llega un mensaje a la página. This method executes whenever a message is sent to our page."""
    sender_id = event.sender_id
    # We see if the message is a text or an attachment (image, GIF, sticker, etc)
    if event.is_text_message:
        # We get the message from the event variable and sent it back7
        page.send(sender_id, "Hey, you send me: {}".format(event.message_text))
    elif event.is_attachment_message:
        page.send(sender_id, "I'm sorry, you have to send me text :). ")


if __name__ == '__main__':
    app.run(host="127.0.0.1", port=5000, debug=True, threaded=True)